services:
    web:
        build: .
        container_name: scoutsbevaixch
        env_file: ".env"
        ports:
            - 80:80
        volumes:
            - ./imgs:/app/imgs
            - ./google_token.json:/app/google_token.json
            - static:/app/static
        restart: unless-stopped

volumes:
    static: